spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create # application ????? ?? ?? ??? ? ??? ?? create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
#        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
  #  org.hibernate.type: trace
  org.hibernate.orm.jdbc.bind: trace